version: 2.1


commands:
   # Exercise - Rollback
   destroy_environment:
     steps:
       - run:
           name: Destroy environment
           # ${CIRCLE_WORKFLOW_ID} is a Built-in environment variable 
           # ${CIRCLE_WORKFLOW_ID:0:5} takes the first 5 chars of the variable CIRCLE_CI_WORKFLOW_ID 
           when: on_fail
           command: |
             aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7}

  
jobs:
  
  # create_infrastructure: 
  #   docker:
  #     - image: amazon/aws-cli  #The job code uses amazon/aws-cli docker image that has AWS CLI installed already. 
  #     # the AWS cli crdentials that we have set up as enviroment variables in the prohect settin on circleci, are used in this image
  #   steps:
  #     - checkout
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file template.yml \
  #             --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #             --region us-east-1


  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: cimg/base:2023.02
    steps:
      - checkout
      - add_ssh_keys:
              
          fingerprints: 
            
            - "6f:19:cc:65:5b:b5:b5:da:69:c8:31:f0:5e:0f:21:13"
      
      
      - run:
          name: Install Ansible
          command: |
            sudo apt install software-properties-common 
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible 

      - run: ansible --version 
     
      - run: 
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml 
      
       
  # Exercise: Smoke Testing
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            URL="https://blog.udacity3333.com/"
            # Test if website exists
            if curl -s --head ${URL} 
            then
              return 0
            else
              return 1
            fi
      - destroy_environment:
          when: on_fail





workflows:
 
  myWorkflow:
    jobs:
      # - create_infrastructure 
      - configure_infrastructure
          # requires:
          #   - create_infrastructure
      - smoke_test