version: 2.1


  
jobs:
  
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli  #The job code uses amazon/aws-cli docker image that has AWS CLI installed already. 
      # the AWS cli crdentials that we have set up as enviroment variables in the prohect settin on circleci, are used in this image
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: 
    steps:
      - checkout
      - add_ssh_keys:
              
              fingerprints: ["59:62:94:1c:eb:0d:c9:1f:2f:32:a0:83:f9:24:bf:78"] 
      - run:
          name: Install Ansible
          command: |
            pip install --user ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook main.yml -i inventory.txt 




workflows:
 
  myWorkflow:
    jobs:
      - create_infrastructure 
      - configure_infrastructure:
          requires:
            -create_infrastructure